    
## *TALLER 1 ANÁLISIS DE ESTRUCTURAS - MATRIZ DE TRANSFORMACIÓN* ##


### El objetivo de este taller es construir la matriz de rigidez en coordenadas locales para elementos tipo cercha y mostrar los cambios que ocurren al variar propiedades geométricas o del material.###

Para el desarrollo de este taller, usaremos la siguiente estructura de acero en la cual los elementos internos tienen un área de 10 cm<sup>2</sup> y los elementos externos tienen un área de 12 cm<sup>2</sup>.



In [5]:
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "Img/Cercha-Taller1.PNG")

Debemos recordar que la matriz de rigidez de un elemento tipo cercha depende solo de tres variables: el área, el módulo de elasticidad y la longitud del elemento. Las unidades en las que ingresemos dichas variables deben ser consistentes entre sí, por lo cual utilizaremos kN y mm.

En la siguiente imagen, se muestra la forma que tiene la matriz de rigidez en coordenadas locales, para un elemento tipo cercha:


In [8]:
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "Img/Matriz_cercha_plana.jpg")

Ingresemos los valores de área, módulo de elasticidad y longitud en las unidades indicadas:

In [3]:
A=700  #mm^2
E=200  #GPa
L=4000 #mm 

In [4]:
import numpy as np
k=np.zeros((4,4))
for i in range(4):
    k[0,0]=k[2,2]=A*E/L
    k[0,2]=k[2,0]=-k[0,0]    
print(k)

[[ 35.   0. -35.   0.]
 [  0.   0.   0.   0.]
 [-35.   0.  35.   0.]
 [  0.   0.   0.   0.]]


Debido a que la rigidez tiene unidades de fuerza sobre longitud, con las unidades ingresadas en el programa, la matriz anterior tendría unidades kN/mm.

***Es importante resaltar, que esta matriz tiene la misma forma para cualquier elemento, sin importar su orientación. Aunque se debe notar que los valores cambiarán dependiendo del elemento que analicemos.***

Cambiemos los valores de las constantes de la matriz para observar la variación de los valores de rigidez de cada elemento. 