<div style="text-align:center"> 
    
## *TALLER 1 ANÁLISIS DE ESTRUCTURAS - MATRIZ DE TRANSFORMACIÓN* ##   
    
</div>


            



### El objetivo de este taller es construir la matriz de rigidez en coordenadas locales para elementos tipo cercha o pórtico, y mostrar los cambios que ocurren al variar propiedades geométricas o del material.###

    




Para el siguiente elemento tipo pórtico tridimensional se determinará la matriz de transformación de coordenadas.

In [1]:
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "Img/Portico_tridimensional.PNG")

In [2]:
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "Img/Portico_tridimensional1.PNG")

In [3]:
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "Img/Portico_tridimensional2.PNG")

Se debe definir las coordenadas del nudo inicial N<sub>i</sub>, y del nudo final N<sub>f</sub> del vector x

In [4]:
Nix=5
Niy=3
Niz=5
Nfx=10
Nfy=6
Nfz=8

A partir de las coordenadas del vector x, se calculará la longitud del vector utilizando el teorema de Pitágoras:

In [5]:
L1=((Nfx-Nix)**2+(Nfy-Niy)**2+(Nfz-Niz)**2)**0.5
print(L1)

6.557438524302


El vector unitario x se calculará a partir de las componentes del vector en cada dirección y de su longitud tal y como sigue

In [6]:
x1=(Nfx-Nix)/L1
y1=(Nfy-Niy)/L1
z1=(Nfz-Niz)/L1
print("x=",x1,"i +",y1,"j +",z1,"z")


x= 0.7624928516630234 i + 0.457495710997814 j + 0.457495710997814 z


Definir y calcular un vector auxiliar unitario x’ que no sea paralelo a x y que x y x’ conformen
un plano dentro del cual se encuentre el eje local y. El eje local z es perpendicular al plano
formado por x y x’, formado por un sistema de mano derecha con x y x’.


¿En qué plano se ubica el vector x’? 

Definir las coordenadas del nudo inicial y del nudo final del vector x'

In [7]:
nix=10
niy=6
niz=0
nfx=5
nfy=3
nfz=5

Notese la diferencia entre las variables definidas para las coordenadas del vector x y del vector x'.

De igual manera, se calculará la longitud de dicho vector y el vector unitario.

In [8]:
L2=((nfx-nix)**2+(nfy-niy)**2+(nfz-niz)**2)**0.5
print(L2)

7.681145747868608


In [9]:
x2=(nfx-nix)/L2
y2=(nfy-niy)/L2
z2=(nfz-niz)/L2
print("x'=",x2,"i +",y2,"j +",z2,"z")

x'= -0.6509445549041194 i + -0.39056673294247163 j + 0.6509445549041194 z


A partir de los vectores x y x' se calculará el vector z, por medio del producto cruz entre ambos vectores

In [10]:
x3=y1*z2-z1*y2
y3=-(x1*z2-z1*x2)
z3=x1*y2-y1*x2
print("z=",x3,"i +",y3,"j +",z3,"z")

z= 0.4764869471456251 i + -0.7941449119093752 j + 0.0 z


A partir del vactor z' se calculará su respectivo vector unitario

In [11]:
L3=(x3**2+y3**2+z3**2)**0.5
print(L3)

0.9261241557759451


In [12]:
print("z=",x3/L3,"i +",y3/L3,"j +",z3/L3,"z")

z= 0.5144957554275266 i + -0.8574929257125442 j + 0.0 z


Conociendo el vector z, se calcula el vector y, definido como el producto cruz entre z y x

In [21]:
x4=y3*z1/L3-z3/L3*y1
y4=-(x3*z1/L3-z3*x1/L3)
z4=x3*y1/L3-y3*x1/L3
print("y=",x4,"i +",y4,"j +",z4,"z")

y= -0.39229933572445613 i + -0.23537960143467368 j + 0.8892118276421006 z


In [22]:
L4=(x4**2+y4**2+z4**2)**0.5
print(L4)

1.0


In [23]:
print("y=",x4/L4,"i +",y4/L4,"j +",z4/L4,"z")

y= -0.39229933572445613 i + -0.23537960143467368 j + 0.8892118276421006 z


Para el desarrollo de la segunda parte del taller, usaremos la siguiente estructura de acero en la cual los elementos internos tienen un área de 10 cm<sup>2</sup> y los elementos externos tienen un área de 12 cm<sup>2</sup>.

In [14]:
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "Img/Cercha-Taller1.PNG")

Debemos recordar que la matriz de rigidez de un elemento tipo cercha depende solo de tres variables: el área, el módulo de elasticidad y la longitud del elemento. Las unidades en las que ingresemos dichas variables deben ser consistentes entre sí, por lo cual utilizaremos kN y mm.

En la siguiente imagen, se muestra la forma que tiene la matriz de rigidez en coordenadas locales, para un elemento tipo cercha:


In [15]:
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "Img/Matriz_cercha_plana.jpg")

Ingresemos los valores de área, módulo de elasticidad y longitud en las unidades indicadas:

In [16]:
A=700  #mm^2
E=200  #GPa
L=4000 #mm 

In [17]:
import numpy as np
k=np.zeros((4,4))
for i in range(4):
    k[0,0]=k[2,2]=A*E/L
    k[0,2]=k[2,0]=-k[0,0]    
print(k)

[[ 35.   0. -35.   0.]
 [  0.   0.   0.   0.]
 [-35.   0.  35.   0.]
 [  0.   0.   0.   0.]]


Debido a que la rigidez tiene unidades de fuerza sobre longitud, con las unidades ingresadas en el programa, la matriz anterior tendría unidades kN/mm.

***Es importante resaltar, que esta matriz tiene la misma forma para cualquier elemento, sin importar su orientación. Aunque se debe notar que los valores cambiarán dependiendo del elemento que analicemos.***

Cambiemos los valores de las constantes de la matriz para observar la variación de los valores de rigidez de cada elemento. 